# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :unit_tests do
    run_tests(
      scheme:"SwiftDemosTests",
      output_directory: "./test_results",
      output_types: "html"
    )
  end

  desc "Run UI Tests"
  lane :ui_tests do
    run_tests(
      scheme:"SwiftDemosUITests",
      output_directory: "./ui_test_results",
      output_types: "html"
    )
  end

  desc "Build App"
  lane :beta do

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_API_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_API_KEY"],
      in_house: false
    )

    match(
      type: "appstore",
      readonly: true,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      keychain_name: "fastlane.keychain",
      keychain_password: ENV["FASTLANE_KEYCHAIN_PASSWORD"]
    )

    commit = last_git_commit
    short_hash = commit[:abbreviated_commit_hash]

    increment_build_number
    
    build_app(
      scheme: "SchematicViewer iOS",
      configuration: "Release",
      output_directory: "./builds",
      output_name: "SchematicViewer-iOS-#{short_hash}.ipa",
      export_method: "app-store",
      export_team_id: "3BT7A38RRX",
      clean: true,
      silent: true
    )

    # update_code_signing_settings(
    #   use_automatic_signing: false,
    #   team_id: "3BT7A38RRX"
    # )

    upload_to_app_store
  end

  desc "Update App Screenshots"
  lane :update_screenshots do
    derived_data_path = 'build/derived_data/snapshots'
    scan(
      clean: true,
      build_for_testing: true,
      derived_data_path: derived_data_path,
      scheme: "SwiftDemosUITests"
    )
    snapshot(
      skip_open_summary: true,
      test_without_building: true,
      derived_data_path: derived_data_path
    )
  end

  desc "Create keychain"
  lane :keychain do
    create_keychain(
      name:"fastlane.keychain",
      password:ENV["FASTLANE_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end
end
